import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "Next14-Proj ",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  


  return (
    <html lang="en">
    <body>
          <Header/>
        {children}
          <Footer/>
     </body>
     </html>
  );
}

// export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
